version: "3.8"
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80

  account-service:
    container_name: account-service
    env_file:
      - ./packages/account-service/.env
    build:
      context: .
      dockerfile: ./packages/account-service/Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./packages/account-service:/usr/app/packages/account-service
    depends_on:
      postgres:
        condition: service_healthy
      db-migrate:
        condition: service_completed_successfully

  collection-service:
    container_name: collection-service
    env_file:
      - ./packages/collection-service/.env
    build:
      context: .
      dockerfile: ./packages/collection-service/Dockerfile
    ports:
      - 8002:8002
    volumes:
      - ./packages/collection-service:/usr/app/packages/collection-service
    depends_on:
      postgres:
        condition: service_healthy
      db-migrate:
        condition: service_completed_successfully

  db-migrate:
    container_name: db-migrate
    build:
      context: .
      dockerfile: ./packages/tools/db-migrate/Dockerfile
    env_file:
      - ./packages/tools/db-migrate/.env
    restart: on-failure:5
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    env_file:
      - ./packages/db/.env
    build:
      context: ./packages/db/
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "taskify", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
