version: "3.8"
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80

  account-service:
    container_name: account-service
    env_file:
      - ./packages/account-service/.env
    build:
      context: .
      dockerfile: ./packages/account-service/Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./packages/account-service:/usr/app/packages/account-service
    depends_on:
      postgres:
        condition: service_healthy

  collection-service:
    container_name: collection-service
    env_file:
      - ./packages/collection-service/.env
    build:
      context: .
      dockerfile: ./packages/collection-service/Dockerfile
    ports:
      - 8002:8002
    volumes:
      - ./packages/collection-service:/usr/app/packages/collection-service
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    env_file:
      - ./packages/db/.env
    build:
      context: ./packages/db/
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "taskify", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      # Persist data on local machine - ./postgres-data:/var/lib/postgresql/data
      - ./packages/db/dumps/:/docker-entrypoint/initdb.d/

volumes:
  dumps:
